### ISSUE TITLE
Venue Page

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#45]
it does not look like markdown. are we making this page markdown or leaving it?

**Comment by Hoverbear** [comment]
It can be made markdown! It hadn't been updated so I hadn't converted it. 

We can remove the contents and make it:

``` hbs
{{#markdown}}
  ### Special Hotel
  **123 Close St.**
  **1-555-555-5555**
  More info!
{{/markdown}}
```

**Comment by DellaPreston** [comment]
cool!!

**Comment by Hoverbear** [comment]
Fixed by @DellaPreston
