### ISSUE TITLE
Key Dates

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#46]
can you add these to the site. I attached a document too, did you get it?

Early Registration Deadline - $150  Wednesday, November 30, 2016

Regular Registration Deadline - $200    Tuesday, January 31, 2017

Registration Fees Due   Tuesday, February 28, 2017

Refunds Honoured Deadline   Tuesday, February 28, 2017

Facilitator Applications Due    Friday, November 4, 2016
-   Facilitator binder to Youth Committee   Thursday, November 10, 2016
-   Youth Committee Meeting Friday, November 18, 2016
-   Facilitators informed if successful Wednesday, November 30, 2016

Career and Education Fair Applications Due  Wednesday, November 30, 2016

Exhibitor informed if successful    Friday, December 9, 2016

Emcee, Keynote, Entertainment Applications Due  Friday, January 20, 2017

Youth Talent Showcase Applications Due
-   Workshop/performance March 22   Friday, March 3, 2017

Honour an Indigenous Youth Champion in Your Community 
-   Youth honoured Friday, March 24th   Friday, March 3, 2017

[GOV2017_KeyDates.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/408026/GOV2017_KeyDates.docx)

**Comment by DellaPreston** [comment]
ohh, I see the document.

**Comment by Hoverbear** [comment]
Is this on the current gatheringourvoices.com or the gov.hoverbear.org instance?

**Comment by DellaPreston** [comment]
for the official gov page not the thank you page.

**Comment by Hoverbear** [comment]
Where do you want these listed?

**Comment by DellaPreston** [comment]
we put these on the FAQs page

**Comment by DellaPreston** [comment]
we put these on the FAQs page. it is okay.

**Comment by Hoverbear** [comment]
Woot =D
