### ISSUE TITLE
dates view

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#47]
hi Andrew, 

dates are showing up as  03/21/2017 until 03/24/2017 

can it show up as March 21, 2017 - March 24, 2017

**Comment by Hoverbear** [comment]
Any date you want to display in that format can be done by changing, for example:

``` hbs
{{date @config.deadlines.facilitator}}
```

To:

``` hbs
{{date @config.deadlines.facilitator formatting="MMM DD, YYYY"}}
```

Whatever you pass inside of `formatting="blah blah blah"` gets passed to `.format()` from [here](http://momentjs.com/docs/#/displaying/format/). You can see there are many many options, but what I've posted above is what you're looking for.

Please be careful where you do this, for example if you do this on some form inputs you will cause bugs. If in doubt just ask. :)
