### ISSUE TITLE
home page button

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#51]
can you add that button that says: directed to the register New Account

Register Now or apply to facilitate, volunteer or exhibit!

directed to the register New Account page

**Comment by Hoverbear** [comment]
Delaying until after infra-rebuild.

**Comment by DellaPreston** [comment]
the home page button says: Interested in getting involved? Become a Volunteer!

can it say: Apply to Facilitate, Volunteer or Exhibit!
