### ISSUE TITLE
documents for GOV site

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#52]
[Keynote.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488933/Keynote.docx)
[RegistrationPackage.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488934/RegistrationPackage.docx)
[YouthTalentShowcase.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488935/YouthTalentShowcase.docx)

these are the document we want on the website. we are not sure where to put them. can you upload them? 
we do not have a poster yet. 
[Keynote.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488936/Keynote.docx)
[RegistrationPackage.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488937/RegistrationPackage.docx)
[YouthTalentShowcase.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488938/YouthTalentShowcase.docx)

[Emcee.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488928/Emcee.docx)
[Entertainment.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488929/Entertainment.docx)
[EventDJ.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488930/EventDJ.docx)
[FundraisingHelp.pdf](https://github.com/BCAAFC/Gathering-Our-Voices/files/488931/FundraisingHelp.pdf)
[HonourAnIndigenousYouth.docx](https://github.com/BCAAFC/Gathering-Our-Voices/files/488932/HonourAnIndigenousYouth.docx)

**Comment by Hoverbear** [comment]
Delaying until after infra-rebuild.

**Comment by Hoverbear** [comment]
You can replace the documents here: https://github.com/BCAAFC/Gathering-Our-Voices/tree/master/static/documents

It's important to make sure they're in the correct format (`pdf`, `docx`) in order to make it a drop-in replacement.

Or just let me do it. :)

**Comment by DellaPreston** [comment]
Yes if you can do it that would be grateful! We had a good day one and two for the funding conference...wild long days.

-Della Preston
Lead Conference Coordinator
BC Association of Aboriginal Friendship Centres
551 Chatham Street, Victoria, BC  V8T 1E1
250.388.5522 ext. 210 or 1.800.990.2432 ext. 210

-------- Original message --------
