### ISSUE TITLE
Footer-CohostLogo

### ISSUE THREAD

**Issue by HannahMashon** [BCAAFC/Gathering-Our-Voices#53]
Uploaded new cohost logo image
Need cohost logo image updated in the home page footer
Re: F943145

**Comment by Hoverbear** [comment]
Requires: Cohost logo in `png` format with a transparent background or an `svg` format logo.

Delaying until after infra-rebuild.

**Comment by Hoverbear** [comment]
Requires: Cohost logo in `png` format with a transparent background or an `svg` format logo.

Delaying until after infra-rebuild.
