### ISSUE TITLE
home page big GOV logo

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#54]
I tried to change the logo on the home page, looks like it did not work. did I save the logo in the wrong spot? 

on slack the red number is fdcf297

**Comment by Hoverbear** [comment]
Correct location is here: https://github.com/BCAAFC/Gathering-Our-Voices/blob/master/static/logos/gov.png

If it's not been done after infra-rebuild I'll move it then. :)

**Comment by Hoverbear** [comment]
Noting that this logo includes black text which the other logo did not. If this is fine please close the issue. If you'd like to use a non-text including version like before please provide it or upload the new version.

**Comment by DellaPreston** [comment]
with the text is fine.
