### ISSUE TITLE
BCAAFC logo

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#56]
can you update the BCAAFC logo on the About Page and  the  Footer?
![bcaafc_logolargetransparent](https://cloud.githubusercontent.com/assets/5642662/18804006/6aa53614-81aa-11e6-9f19-a1d73b2de812.png)

![bcaafc_logo_small-alternate](https://cloud.githubusercontent.com/assets/5642662/18804025/95b8b9e8-81aa-11e6-9190-701c1ce87960.png)

**Comment by Hoverbear** [comment]
Delaying until after infra-rebuild.

**Comment by Hoverbear** [comment]
The logo on the `/about` page is SVG. Can you please provide this?

**Comment by DellaPreston** [comment]
I tried to attach svg Github says :We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by DellaPreston** [comment]
I sent an email with svg.
