### ISSUE TITLE
volunteer form correct dates

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#59]
FAQs page - how do I correct the dates that are in the squgally things {{dsfdsfsd}}

currently it reads When and where is the Conference happening this year? Gathering Our Voices will be in Kelowna, BC from 03/21/2017 until 03/24/2017 at the Delta Grand Okanagan Resort and Conference Centre and other venues around the city.

can you change those dates to read March 21-24, 2017

**Comment by Hoverbear** [comment]
You don't correct those. It's a configuration file with very strict syntax, any error would break the entire application.

The dates are already correct, you are referring to a formatting change which was detailed in https://github.com/BCAAFC/Gathering-Our-Voices/issues/47#issuecomment-242930673

Fix incoming.
