### ISSUE TITLE
date correction

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#60]
general facilitator information:
 can you correct the date below in the {{ sdfdf }}} needs to be November 4, 2016 

ntial Facilitators <strong>must call Della, 250-388-5522 ext. 210, before {{date @config.deadlines.facilitator}}</strong> to verify their application before it is considered by the youth steering committee.</li>
  <li>Facilitators are informed if they were chosen to host a workshop: December9, 2016</li>
  <li>You will also receive a confirmation email that you submitted an application. Be sure you receive that in your inbox or

**Comment by Hoverbear** [comment]
Please work on improving clarity in writing issues. It took me a solid 10 minutes to even understand what you were referring to.

**Comment by Hoverbear** [comment]
Fixed in infra, change happening soon.
