### ISSUE TITLE
Registration Form - Payment Due Date incorrect

### ISSUE THREAD

**Issue by HannahMashon** [BCAAFC/Gathering-Our-Voices#63]
Registration Form currently states: Payment is due February 29, 2016.

Can you please change it to Payment is due February 28, 2017.

This date is also incorrect on the FAQs page. Please change to February 28, 2017.

**Comment by Hoverbear** [comment]
FAQ was already right:
![screen shot 2016-09-28 at 00 44 34](https://cloud.githubusercontent.com/assets/130903/18894710/c4ccc1c6-8514-11e6-8526-eb5bdc930af0.png)

Updated the payments page.
