### ISSUE TITLE
capacity limit home page progress bar

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#66]
I pulled dialogue from an email: 

Ohh, my error. I was checking checking stats…I want to count 1000 youth between ages 14- 24 years and the chaperones 24 years plus are not counted in the 1000 counter. 

Is that possible  to make that distinction with the counter?

If not can you put the capacity limit back to 1200 for overall. I am watching the numbers climb!

-Della Preston
Lead Conference Coordinator, BCCAFC
W: 250-388-5522 or 1-800-990-2432 Ext. 210

From: Andrew Hobden [mailto:andrew@hoverbear.org] 
Sent: September 26, 2016 1:16 PM
To: Della Preston DPreston@bcaafc.com
Subject: Re: BCAAFC - Gathering Our Voices 2017 Registration is Open

It was 1200, changed to 1000. Reminder that this is a soft cap and registration must be closed manually just like last year.

On Mon, Sep 26, 2016 at 9:02 PM, Della Preston DPreston@bcaafc.com wrote:
Cool graphs!

Can you confirm the 1000 youth capacity limit is in place?

**Comment by Hoverbear** [comment]
It's all members. :) I'll set the cap to 1200 because of this.
