### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#67]
1. large blue button New Text: 

Register Now to apply to facilitate, volunteer or exhibit! 
1. replace counter progress bar was replaced with Registration is Open - New Dates and New Deadlines
   Early Registration deadline November 30, 2016   BUT can it read: 

Registration is Closed 
We have reached full capacity for the conference in Kelowna 2017. Join our distribution list for updates on GOV 2018.

**Comment by Hoverbear** [comment]
You don't need to email and post an issue about this. :)

**Comment by DellaPreston** [comment]
I realized....I need to remember to only post things in issues not emails.

-Della Preston
Lead Conference Coordinator
BC Association of Aboriginal Friendship Centres
551 Chatham Street, Victoria BC V8T 1E1
250.388.5522 or 1.800.990.2432 ext. 210

**Comment by Hoverbear** [comment]
=D!
