### ISSUE TITLE
Exhibitor Application Form

### ISSUE THREAD

**Issue by HannahMashon** [BCAAFC/Gathering-Our-Voices#68]
Remove the "payment method" drop down menu at the bottom of the form
Input text "Exhibitor payments due upon approval. Applicants will be notified December 9th, 2016"

**Comment by DellaPreston** [comment]
if you can not remove the drop down, can you change the text above. I know changing the Form can be difficult at this point.

**Comment by Hoverbear** [comment]
Probably easiest just to leave it. :) I don't think it's causing any harm.

Fixed in https://github.com/BCAAFC/Gathering-Our-Voices/commit/bda4e834cd023bd5fe72fbe388f356619c6ecf96
