### ISSUE TITLE
Markdown space between buttons for text

### ISSUE THREAD

**Issue by HannahMashon** [BCAAFC/Gathering-Our-Voices#72]
Can we create a markdown text option between each of the buttons on the index page.
example: 
##Registration Package
- Supporting text
"registration package button"

##Honour a Youth
- Supporting text
"Honour a  youth application button"

##Talent Showcase
-Supporting Text
"Talent showcase application button" 

Etc.... also for Emcee, keynote, entertainment, DJ

**Comment by Hoverbear** [comment]
It works already. :)

``` html

  <div class="text-center">
      <a class="btn btn-primary btn-block" target="_blank" href="/documents/registration.docx">
        Registration Package
      </a>

      Blah **blah** blah.

      <a class="btn btn-primary btn-block" target="_blank" href="/documents/honour.docx">
        Honour A Youth
      </a>
```

![screen shot 2016-11-15 at 19 29 01](https://cloud.githubusercontent.com/assets/130903/20318260/c99314f0-ab69-11e6-8a5b-2c8dd185c4a7.png)
