### ISSUE TITLE
workshops approved button

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#76]
Hi Andrew, 

can you look at the workshops approved button.

When we click on it it does not approve the workshop.

**Comment by Hoverbear** [comment]
Confirmed, looks like something got misaligned on the table.

**Comment by Hoverbear** [comment]
Fixed in https://github.com/BCAAFC/Gathering-Our-Voices/commit/42155bf55f602e9415484beffa8f655ab1018417, looks like I can't count. :)
