### ISSUE TITLE
workshop express interest

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#81]
when you click the workshop express interest button it gives
![workshopregistration](https://cloud.githubusercontent.com/assets/5642662/21939056/e921a944-d972-11e6-9de2-625cde48a0dd.png)
 you 2 fields to fill: Email* and Secret*

Email*
who email is that, is it the primary contacts email?

Secret*
what goes here, the kids name?

**Comment by Hoverbear** [comment]
On completed members you'll see this:

<img width="1372" alt="screen shot 2017-01-13 at 20 04 31" src="https://cloud.githubusercontent.com/assets/130903/21941992/8b18d51c-d9cb-11e6-9f7a-473aa2ebc27f.png">

So they enter the email from their details and the code. :)
