### ISSUE TITLE
GOV website Request Change Process or Error Report

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#82]
Hi Andrew, 

in preparation for my departure what do you think of this little form to help GOV team complete. 
1. GOV team member would complete the little form and send to Hannah.  
2. Hannah can either do the change herself  OR Submit the change or error notice on GitHub Issues.

**GOV website Request Change Process or Error Report**
Send request via GitHub – Hannah can do this
Please include:
Question:

1. Person requesting change:
2. What website page the change need to happen on:
3. Identify location and what exist currently and what it should be replaced with:	
4. If an error occurred what date and time it occurred:
5. Who’s account you were logged in as:
6. What was click and the outcome, provide screen shot if possible:
7. Expected outcome:
8. desired date and time for the change or correction to be completed:

**Comment by Hoverbear** [comment]
Seems great to me.
