### ISSUE TITLE
workshop waivers

### ISSUE THREAD

**Issue by HannahMashon** [BCAAFC/Gathering-Our-Voices#87]
Where would you like the PDF waivers to be uploaded in GitHub for workshops?
We will need to link the waivers to the correlating workshop descriptions.

**Comment by Hoverbear** [comment]
Here please: https://github.com/BCAAFC/Gathering-Our-Voices/tree/master/static/documents/waivers

Links should be to `/documents/waivers/example_waiver.pdf`
